### ISSUE TITLE
Overlay showing current configuration

### ISSUE THREAD

**Issue by gtjamesa** [Syhlex/chugging-barrel#2]
I think it would be useful to show an overlay on the chug jug in your inventory (similar to the potion names plugin) that will show the loadout name or the first three potion names if none are selected

When "Load" is pressed, the current loadout (name + pots) can be stored to config so it will remain on client refresh

Crude example:

![image](https://github.com/user-attachments/assets/06a94512-184f-4d6a-bc6a-a5998932ab6e)

**Comment by Syhlex** [comment]
Good idea, will look into it.

**Comment by Syhlex** [comment]
@gtjamesa Implemented the following changes in v1.1.0:
- Sets the selected loadout to config when "Load" button is clicked.
- Displays the first 7 chars of the selected loadout over the chugging barrel.
- Clears the selected loadout when the "Deposit Potions" button is clicked.

**Comment by gtjamesa** [comment]
> @gtjamesa Implemented the following changes in v1.1.0:
> - Sets the selected loadout to config when "Load" button is clicked.
> - Displays the first 7 chars of the selected loadout over the chugging barrel item.
> - Clears the selected loadout when the "Deposit Potions" button is clicked.

Amazing thank you - I'll check it out today!

**Comment by gtjamesa** [comment]
Hey man, got caught up in leagues and totally forgot to get back to you on here. The update works flawlessly, thank you!
